version: '2'
services:
  app:
    image: docker.moxa.online/moxaisd/device:${VERSION}-${ARCH}
    restart: unless-stopped
    privileged: true
    network_mode: "host"
    extra_hosts:
      - moxa:127.0.0.1
    volumes:
      # DEVICE APP ENV : modify following parameter if you know what you ar doing.
      - ${APPMAN_APPPATH}/moxaenv:/tmp/moxaenv
      - /etc/:/host/etc/
      - /usr/share/:/host/usr/share/
      # [ kversion ]
      - /bin/kversion:/bin/kversion
      - /usr/bin/fw_printenv:/usr/bin/fw_printenv
      - /etc/fw_env.config:/etc/fw_env.config
      # [ cellular ]
      - /var/run/moxa-cellular-utils/:/var/run/moxa-cellular-utils/

networks:
  appservice:
    external:
      name: appservice
